PKG_TYPE_DATA = 1
PKG_TYPE_HELLO = 2
PKG_TYPE_ACK = 3

PKG_TYPE_SIZE = 4
PKG_NUM_SIZE = 4
DATA_LEN_SIZE = 4
DATA_HASH_SIZE = 4

TOTAL_HEADER_SIZE = PKG_TYPE_SIZE + PKG_NUM_SIZE + DATA_LEN_SIZE + DATA_HASH_SIZE

CHUNK_SIZE = 16
IV_SIZE = 16